[package]
name = "nex-fih"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
fih-model = { path = "../../fih" }
nex-core = { path = "../core" }
nex-io = { path = "../io" }
chton.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2 = "0.10"
petgraph = { version = "0.6", features = ["serde-1"] }
tagma-core = { git = "https://github.com/ssccsorg/syntagma", branch = "main" }
postcard = { version = "1", features = ["alloc"] }
futures-executor = "0.3"
async-trait.workspace = true
log.workspace = true
