[workspace]
resolver = "2"
members = [
    "fih",
    "nex-server/server",
    "nex-server/client",
    "nexd",
    "libs/serde-proxy",
    "libs/session-server",
    "libs/async-store",
    "playbooks/agents",
    "interface/query",
    "storage/sim",
    "apps/nex-calc",
    "benches",
    "verify/support",
    "verify/osless",
    "verify/mcu",
    ]
exclude = [
    "apps/nex-wasmer-ssccsdocs",
    "apps/nex-spinwasi-ssccsdocs",
    "apps/nex-tagma",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
log = "0.4"
async-trait = "0.1"
chton = { git = "https://github.com/ssccsorg/chton", branch = "181-no-std", default-features = false }
tagma-core = { git = "https://github.com/ssccsorg/syntagma", branch = "181-tagma-geo-nostd" }
tagma-map = { git = "https://github.com/ssccsorg/syntagma", branch = "181-tagma-geo-nostd" }

[profile.release]
lto = "thin"
codegen-units = 1
opt-level = 3

[profile.dev]
opt-level = 1
