tunnel: 0d95c7af-bdeb-4cec-b801-b5ea3e43c33b

ingress:
  - hostname: graph-api-dev.nexus.ssccs.org
    service: http://127.0.0.1:7689
    originRequest:
      noTLSVerify: true
      connectTimeout: 10s
      tcpKeepAlive: 30s
      readTimeout: 120s
      writeTimeout: 120s

  - service: http_status:404
