tunnel: fe6dbde1-4bf1-4096-8f15-f8cc8fb16b87

ingress:
  - hostname: graph-api-dev.nexus.ssccs.org
    service: http://127.0.0.1:7689
    originRequest:
      noTLSVerify: true
      connectTimeout: 10s
      tcpKeepAlive: 30s
      readTimeout: 120s
      writeTimeout: 120s

  - service: http_status:404
