name: nex-wasmer-ssccsdocs
app_id: da_KgYIZt9Uoa0G
owner: metasmile
package: .
env:
  DATA_DIR: /data/fih
  DOCS_DIR: /data/docs
  PROJECT: wasmer-ssccsdocs
  PORT: '3000'
capabilities:
  instaboot:
    mode: null
    requests:
    - path: /
volumes:
- name: fih-data
  mount: /data/fih
- name: docs-data
  mount: /data/docs
debug: true
kind: wasmer.io/App.v0
