name: nex-wasmer-ssccsdocs
app_id: da_KgYIZt9Uoa0G
owner: metasmile
package: .
env:
  DATA_DIR: /data/fih
  DOCS_DIR: /data/docs
  PROJECT: wasmer-ssccsdocs
capabilities:
  instaboot:
    mode: null
    requests:
    - path: /
volumes:
- name: fih-data
  mount: /data/fih
- name: docs-data
  mount: /data/docs
debug: true
kind: wasmer.io/App.v0
annotations:
  shipitcli.com/config:
    commands: {}
    convert_redirects: true
    port: 8080
    sws_version: 2.38.0
  shipitcli.com/provider: staticfile
  shipitcli.com/version: 0.21.4
