// Generated from docs.ssccs.org/llms.txt (docs/_llms/llms.txt, 2026-08-26).
// (section, area, title): the real SSCCS documentation manifest used by the
// kb_lifecycle scenario (issue #179). Section and area derive from the URL path.
pub const LLMS_DOCS: &[(&str, &str, &str)] = &[
    ("code_of_conduct", "code_of_conduct", "Code of Conduct"),
    ("contributing", "contributing", "Contributing"),
    ("index", "index", "SSCCS Documentation"),
    ("axioms", "index", "Axioms"),
    ("axioms", "manifesto", "Manifesto"),
    ("axioms", "ssccs", "SSCCS"),
    ("direction", "sc", "Beyond Assembly: a Silicon Compiler"),
    ("direction", "index", "Direction"),
    ("direction", "ecosys", "Ecosystem Skeleton"),
    ("legal", "index", "Charter and Statute"),
    (
        "notes",
        "report_deepseek_spatiotemporal_2608",
        "Analysis: A Programming Paradigm for Spatiotemporal Composability from DeepSeek",
    ),
    (
        "notes",
        "llvm_opt_riscv",
        "Compiler Performance Regression and Deterministic Execution",
    ),
    (
        "notes",
        "eurollvm26_insight",
        "EuroLLVM 2026 Deep Analysis and Insights",
    ),
    (
        "notes",
        "forgeugc_insight",
        "FORGE-UGC Compiler Architecture Conceptual Insights",
    ),
    (
        "notes",
        "iclr26_insight",
        "ICLR 2026 Research Unified Technical Insights",
    ),
    (
        "notes",
        "initial_scheme_alignments",
        "Initial Scheme Alignments",
    ),
    (
        "notes",
        "potential_synergies_with_sponge_functions_and_memristive_dynamics",
        "Potential Synergies with Sponge Functions and Memristive Dynamics",
    ),
    (
        "notes",
        "rust_zerocost_abstractions_immutability_and_the_path_to_observationcentric_hardware",
        "Rust as the Stepping Stone for SSCCS: Zero-Cost Abstractions, Immutability, and the Path to Observation-Centric Hardware",
    ),
    ("notes", "spatz_insight", "Spatz–SSCCS Structural Insights"),
    ("notes", "stream_silicon_insight", "Stream-Adaptive Silicon"),
    (
        "notes",
        "tiletensor_insights",
        "Technical Insights from TileTensor",
    ),
    (
        "notes",
        "timesfm_architectural_insights",
        "TimesFM Architectural Insights for SSCCS",
    ),
    ("notes", "open_format", "Open Formats into Machine Code"),
    ("philosophy", "relation", "From Division to Relation"),
    (
        "philosophy",
        "tri",
        "Ontology, Relationality, Actualization",
    ),
    ("philosophy", "index", "Philosophy"),
    ("philosophy", "pre_linguistic", "Pre-Linguistic Computation"),
    ("philosophy", "epistemology", "Structural Observation"),
    ("projects", "index", "Projects"),
    ("projects", "actus", "Actus"),
    ("projects", "chton", "Chton"),
    ("projects", "chton", "Space-Grade Storage"),
    (
        "projects",
        "chton",
        "esp32-ai Flash Origin Insights for Chton",
    ),
    ("projects", "ev", "CVA6 CV-X-IF Report (Standard Reference)"),
    ("projects", "ev", "ExaVerif"),
    ("projects", "ev", "Ibex RV32IMCB Report"),
    ("projects", "nexus", "Development"),
    ("projects", "nexus", "Executive Summary"),
    ("projects", "nexus", "neXus"),
    ("projects", "nexus", "Proof by Structure"),
    ("projects", "nexus", "Simulation Suite"),
    ("projects", "nexus", "Apps Ecosystem"),
    ("projects", "nexus", "nex-calc"),
    ("projects", "nexus", "nex-cf"),
    ("projects", "nexus", "nex-icp"),
    ("projects", "nexus", "nex-nix"),
    ("projects", "nexus", "nex-tagma"),
    ("projects", "nexus", "nex-zed"),
    ("projects", "nexus", "nex-ros"),
    ("projects", "nexus", "synTagma Integration"),
    ("projects", "nexus", "ACP in the Research-Verification Loop"),
    (
        "projects",
        "nexus",
        "Blackboard Decentralization: Stigmergy over Distributed State",
    ),
    ("projects", "nexus", "Gap-Based Reward System"),
    ("projects", "nexus", "OpenROAD as a Recursive Colony Agent"),
    (
        "projects",
        "nexus",
        "QiMeng Insight Analysis & Multi-Agent Autonomous Research Landscape",
    ),
    (
        "projects",
        "nexus",
        "Stigmergic LLM Contextual Problem Solving",
    ),
    ("projects", "nexus", "Tagma Structural Indexing"),
    (
        "projects",
        "nexus",
        "TokenSpeed Architectural Insights for SSCCS neXus",
    ),
    (
        "projects",
        "nexus",
        "Why neXus Outscales Centralized Approaches",
    ),
    ("projects", "sdbs", "SDBS"),
    ("projects", "sdbs", "Single-Path Artifact Pipeline"),
    ("projects", "sdbs", "The Living Corpus"),
    ("projects", "syntagma", "Executive Summary"),
    ("projects", "syntagma", "synTagma"),
    ("projects", "syntagma", "FPGA"),
    ("projects", "syntagma", "Hardware"),
    ("projects", "syntagma", "Memory"),
    ("projects", "syntagma", "RTL"),
    ("projects", "syntagma", "Synthesis"),
    ("projects", "syntagma", "Identification"),
    ("projects", "syntagma", "Reference Implementations"),
    ("projects", "syntagma", "Software"),
    ("projects", "syntagma", "Security"),
    ("projects", "syntagma", "Serialization"),
    ("projects", "syntagma", "Signal"),
    ("projects", "syntagma", "Tagma"),
    ("projects", "syntagma", "Tagma Geo"),
    ("projects", "syntagma", "Tagma Map"),
    (
        "report",
        "diagnosis",
        "Diagnosis Report: Technical Assessment & Strategic Roadmap",
    ),
    (
        "report",
        "feasibility",
        "Implementation Feasibility Report: Software",
    ),
    (
        "report",
        "provenance_strategy",
        "Intellectual Property Protection Through Verifiable Provenance",
    ),
    ("report", "poc_diagnosis", "PoC Diagnosis and Roadmap"),
    (
        "report",
        "project_stack",
        "Strategic Agentic Development Stack for SSCCS",
    ),
    ("research", "riscv", "RISC-V Integration Research"),
    (
        "research",
        "rust_baremetal",
        "Rust Bare‑Metal Toolchain as a Foundation for RISC-V Integration",
    ),
    (
        "research",
        "scheme_abstraction_layer",
        "Scheme Abstraction Layer: Dimensional Axes, Structural Relations, and Memory Layout",
    ),
    (
        "research",
        "riscv_space",
        "Space Computing: Radiation-Tolerant RISC‑V and SSCCS",
    ),
    (
        "whitepaper",
        "whitepaper",
        "Schema–Segment Composition Computing System",
    ),
    (
        "whitepaper",
        "notes",
        "Technical Proposal for Enhancing the SSCCS Whitepaper",
    ),
    (
        "whitepaper",
        "notes",
        "WhitePaper Review: Technical Consistency and Independence of the SSCCS Paradigm",
    ),
    (
        "works",
        "proposal",
        "A Foundation for Energy-Efficient and Trustworthy Computing",
    ),
    (
        "works",
        "openhw_integration",
        "SSCCS Validation with OpenHW CORE-V Ecosystem",
    ),
    (
        "works",
        "aws",
        "SSCCS × AWS Strategic Collaboration Roadmap",
    ),
    ("works", "index", "Works"),
    ("works", "cern", "CERN-SSCCS Collaboration Framework"),
    (
        "works",
        "cern",
        "Coordinate-indexed addressing for ROOT TTree I/O overhead",
    ),
];
